### ISSUE TITLE
ImportError: no module 'dj_database_url'

### ISSUE THREAD

**Issue by klmmmv** [Forum-Informationsfreiheit/offenewahlen_api#127]
Ich kann die app nicht mehr ausführen.

~~~bash
python src/manage.py runserver
Traceback (most recent call last):
  File "src/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/valentin/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/valentin/.local/lib/python3.5/site-packages/django/core/management/__init__.py", line 307, in execute
    settings.INSTALLED_APPS
  File "/home/valentin/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 56, in __getattr__
    self._setup(name)
  File "/home/valentin/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/home/valentin/.local/lib/python3.5/site-packages/django/conf/__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 673, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/valentin/github/offenewahlen-nrw17/src/offenewahlen_nrw17/settings.py", line 13, in <module>
    import dj_database_url
ImportError: No module named 'dj_database_url'
~~~

Das Modul ist ist installiert. Und nach Internetrecherche ist alles so wie es sein soll. Jemand eine Idee was ich falsch gemacht habe?

**Comment by skasberger** [comment]
virtualenv ist aktiviert, oder?

**Comment by skasberger** [comment]
@tobias47n9e weißt du da was? ist das ein ähnliches Problem wie bei @frocentus ?

**Comment by tobias47n9e** [comment]
Vielleicht nach dem aktivieren der Venv nochmal sicherheitshalber:

    pip install -r requirements.txt

ausführen?

Bei aktivierter venv kann man auch die Konsole mit `python` starten (Ist dann auch gleich Python3). Dann kann man mal probieren ob das Modul zum importieren geht:

    >>> import dj_database_url

**Comment by klmmmv** [comment]
Ich kann den Fehler zumindest bei mir am Laptop nicht reproduzieren. Der Fehler trat bei meinem Desktop PC auf. Ich schließe das Issue deshalb.
